name = "shorturl-worker"
main = 'index.js'
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2024-10-10"
kv_namespaces = [
  { binding = "SUPAFLARE1", id = "af3a8d03414540568a25018fef5bc670", preview_id = "78c8caceaf6b4228aea01f725ef70527" },
]
